config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # The homepage should be a landing page for either new users
  # or a dashboard for existing users
  root 'pages#home'

  # Callback for logging in with 42 will create a session,
  # logging out will destroy one
  get '/auth/marvin/callback', to: 'sessions#create'
  get '/auth/failure',         to: 'sessions#failure'
  delete '/logout',            to: 'sessions#destroy'

  # Protection against unauthorized access in config/initializers/good_job.rb
  mount GoodJob::Engine => 'good_job'

  # We are not doing resourceful routing here because the user
  # you will be editing or updating is always clear, it is the
  # current user. For #new and #create, bindings also do not matter.
  get    '/users/new', to: 'users#new',     as: 'new_user'
  post   '/users',     to: 'users#create',  as: 'create_user'
  get    '/users',     to: 'users#edit',    as: 'edit_user'
  patch  '/users',     to: 'users#update',  as: 'update_user'
  delete '/users',     to: 'users#destroy', as: 'destroy_user'

  # We do some implicit routing here
  # When adding other routes, put them above this one
  # to avoid this catch-all from taking the request instead.
  get '/:year',      to: 'years#show', as: 'year'
  get '/:year/:day', to: 'days#show',  as: 'year_day'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :participations, class_name: 'Participant', dependent: :destroy
  has_many :years, through: :participations
  has_many :stars, through: :participations

  has_and_belongs_to_many :coalitions

  belongs_to :coalition, optional: true

  default_scope { includes(:coalition) }

  validates :aoc_user_id, format: {
                            with: /\A\d+\z/, message: 'Only digits (0-9) allowed'
                          },
                          uniqueness: true,
                          allow_nil: true
  validates :username, presence: true, uniqueness: true
  validates :coalition, inclusion: { in: ->(user) { user.coalitions }, allow_nil: true }

  before_validation :remove_hashtags
  before_save       :choose_default_coalition

  extend FortytwoIntra

  # Instantiates a new user from data we get out of the 42 API for
  # a specific username. This user will not be saved to the database
  # yet, so we can add their AoC ID to it beforehand.
  def self.from_42_api(username)
    api_response = fortytwo_api_client.get("/v2/users/#{username}")

    return User.new(
      username: api_response.login,
      full_name: api_response.usual_full_name,
      photo_url: api_response.image&.versions&.medium
    )
  end

  def intra_url
    return "https://profile.intra.42.fr/users/#{username}"
  end

  private

  def remove_hashtags
    aoc_user_id.remove!("#") if aoc_user_id
  end

  def choose_default_coalition
    if !coalition && coalitions.any?
      self.coalition = coalitions.first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user
  before_action :current_user_is_admin, only: [:new, :create]

  def new
    @user = User.new
    render 'users/_new', layout: 'no_turbo_frame'
  end

  def create
    @user = User.from_42_api(params[:user][:username])
    @user.aoc_user_id = params[:user][:aoc_user_id]

    if @user.save
      render 'users/_success'
    else
      render 'users/_new'
    end
  end

  def edit
    @user = current_user
    render 'users/_edit', layout: 'no_turbo_frame'
  end

  def update
    @user = current_user

    if @user.update(user_params)
      # To avoid complications with data, we destroy the
      # user's old participation if their id has changed and if
      # we can find one in the current year. The next scoreboard
      # sync will repopulate the leaderboard with their new data.
      if @user.aoc_user_id_previously_changed? && @user.aoc_user_id_previously_was &&
          @user.participations.find_by(year: Year.find_by(number: Time.now.year))
        @user.participations.find_by(year: Year.find_by(number: Time.now.year)).destroy
        flash.now[:warning] = "Your old data for #{Time.now.year} has been removed. Your new data will be backfilled at the next scoreboard update."
      end
      render 'users/_success'
    else
      render 'users/_edit'
    end
  end

  def destroy
    @user = current_user

    log_out # Ensure the user is not logged in anymore!
    @user.destroy

    flash[:notice] = 'Successfully removed your account from the systems.'
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:aoc_user_id, :coalition_id)
  end

  def signed_in_user
    redirect_to root_url unless logged_in?
  end

  def current_user_is_admin
    unless current_user.admin?
      flash[:danger] = 'You must be an admin to perform this action!'
      redirect_to root_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def join_code
    ENV.fetch("AOC_LEADERBOARD_JOIN_TOKEN") { "[No token found, please update env vars]" }
  end
end

app/views/users/_edit.html.erb
<turbo-frame id="edit-user-frame">
  <% if logged_in? %>
    <div class="row justify-content-end" id="edit-user-form-div">
      <div class="col-md-8 col-lg-6 col-xl-4">
        <%= bootstrap_form_with model: current_user, url: update_user_url, method: 'patch' do |f| %>
          <div class="card">
            <div class="card-header container-fluid">
              <div class="row">
                <div class="col-10">
                  <span class="fw-bold">Edit Advent of Code user ID</span>
                </div>
                <div class="col-2 text-end">
                  <button type="button" class="btn-close" aria-label="Close" onclick="document.getElementById('edit-user-form-div').remove();"></button>
                </div>
              </div>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <span class="text-secondary">
                  <p>
                    To appear on the leaderboard, you need to link your
                    Advent of Code account to your 42 account.
                  </p>
                  <p>
                    You can find your AoC user ID as follows:
                    <ol>
                      <li>
                        Go to <a href="https://adventofcode.com" target="_blank">adventofcode.com</a> and log in.
                      </li>
                      <li>
                        <div data-controller="leaderboard">
                          Go to the <a href="https://adventofcode.com/<%= page_year %>/leaderboard/private" target="_blank">private leaderboards</a>
                          page and join our leaderboard with code <code id="leaderboard-id"><%= join_code %></code>.
                          <a class="text-primary link-underline link-underline-opacity-0" data-leaderboard-target="link" data-turbo-target="none" data-turbo="false" data-action="click->leaderboard#copy">
                            <i class='bi-clipboard' data-action='click->leaderboard#copy' data-leaderboard-target='icon'></i>
                            <span data-leaderboard-target="span"></span>
                          </a>
                        </div>
                      </li>
                      <li>
                        Go to your settings <a href="https://adventofcode.com/<%= page_year %>/settings" target="_blank">here.</a>
                      </li>
                      <li>
                        Your account ID is the number where it says "(anonymous user #000)".
                        Copy this number into the box below.
                      </li>
                    </ol>
                  </p>
                </span>
              </li>
              <li class="list-group-item">
                <%= f.text_field :aoc_user_id, label: 'User ID' %>
              </li>
              <% if current_user.coalitions.count > 1 %>
                <li class="list-group-item">
                  <p class="text-secondary">
                    You have multiple coalitions on record, so you can change
                    which one your points go to here.
                  </p>
                  <%= f.collection_select :coalition_id, current_user.coalitions, :id, :name %>
                </li>
              <% end %>
            </ul>
            <div class="card-footer">
              <%= f.submit class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <%end %>
</turbo-frame>

app/views/users/_empty_frame.html.erb
<turbo-frame id="edit-user-frame">
</turbo-frame>

app/views/users/_new.html.erb
<turbo-frame id="edit-user-frame">
  <div class="row justify-content-end" id="edit-user-form-div">
      <div class="col-md-8 col-lg-6 col-xl-4">
        <%= bootstrap_form_with model: @user, url: create_user_url, method: 'post' do |f| %>
          <div class="card">
            <div class="card-header container-fluid">
              <div class="row">
                <div class="col-10">
                  <span class="fw-bold">Manually Create User</span>
                </div>
                <div class="col-2 text-end">
                  <button type="button" class="btn-close" aria-label="Close" onclick="document.getElementById('edit-user-form-div').remove();"></button>
                </div>
              </div>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <span class="text-secondary">
                  <p>
                    When inviting users, make sure they join the leaderboard
                    with code <code><%= join_code %></code>, then ask them for
                    their Advent of Code user ID.
                  </p>
                  <p>
                    You can find the ID by going to <a href="https://adventofcode.com/<%= page_year %>/settings" target="_blank">settings</a>,
                    then copy-pasting the number where it says "(anonymous user #000)".
                  </p>
                </span>
              </li>
              <li class="list-group-item">
                <%= f.text_field :username, label: '42 Username' %>
                <%= f.text_field :aoc_user_id, label: 'Advent of Code User ID' %>
              </li>
            </ul>
            <div class="card-footer">
              <%= f.submit class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</turbo-frame>

app/views/users/_success.html.erb
<turbo-frame id="edit-user-frame">
  <div class="col-md-10 offset-md-1 my-2">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>Your Advent of Code user ID has been successfully updated!</strong>
      It may take up to twenty minutes for the scoreboard to sync your stars.
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>

  <%= render 'layouts/flash' %>
</turbo-frame>