config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # The homepage should be a landing page for either new users
  # or a dashboard for existing users
  root 'pages#home'

  # Callback for logging in with 42 will create a session,
  # logging out will destroy one
  get '/auth/marvin/callback', to: 'sessions#create'
  get '/auth/failure',         to: 'sessions#failure'
  delete '/logout',            to: 'sessions#destroy'

  # Protection against unauthorized access in config/initializers/good_job.rb
  mount GoodJob::Engine => 'good_job'

  # We are not doing resourceful routing here because the user
  # you will be editing or updating is always clear, it is the
  # current user. For #new and #create, bindings also do not matter.
  get    '/users/new', to: 'users#new',     as: 'new_user'
  post   '/users',     to: 'users#create',  as: 'create_user'
  get    '/users',     to: 'users#edit',    as: 'edit_user'
  patch  '/users',     to: 'users#update',  as: 'update_user'
  delete '/users',     to: 'users#destroy', as: 'destroy_user'

  # We do some implicit routing here
  # When adding other routes, put them above this one
  # to avoid this catch-all from taking the request instead.
  get '/:year',      to: 'years#show', as: 'year'
  get '/:year/:day', to: 'days#show',  as: 'year_day'
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :year
  has_many   :stars, dependent: :destroy

  validates :number, presence: true, uniqueness: { scope: :year }

  def puzzle_url
    return "https://adventofcode.com/#{self.year.number}/day/#{self.number}"
  end

  def start_time
    return Time.utc(self.year.number, 12, self.number, 5)
  end

  def end_time
    return self.start_time + 1.day
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def show
    @day = Year.find_by!(number: params[:year])
               .days.includes(stars: { participant: { user: :coalition } })
               .find_by!(number: params[:day])
  end
end

app/helpers/days_helper.rb
module DaysHelper
  # The  users that have not yet completed this
  # puzzle are the ones that have not yet gotten
  # the silver star.
  def count_incomplete(day)
    num_participants = day.year.participants.count
    num_silver = day.stars.where(index: 1).count

    return num_participants - num_silver
  end

  # The user count that is currently on silver is the
  # silver count minus the gold count.
  def count_silver(day)
    num_silver = day.stars.where(index: 1).count
    num_gold = day.stars.where(index: 2).count

    return num_silver - num_gold
  end

  # For the gold count, we can just count the gold stars
  # for this day.
  def count_gold(day)
    num_gold = day.stars.where(index: 2).count

    return num_gold
  end

  # For when we need the absolute total of silver stars,
  # rather than the participant count who only have this star.
  def count_silver_stars(day)
    return day.stars.where(index: 1).count
  end

  def top_speeds(day, index = 2, n = 3)
    stars = day.stars.includes(participant: { user: :coalition }).where(index: index)
                     .order(completed_at: :asc).limit(n)

    return stars
  end

  def rank_for_participant(day, participant)
    top_star = day.stars.where(participant: participant).order(index: :desc).first

    if !top_star
      "Incomplete"
    elsif top_star.index == 2
      "Gold + Silver"
    else
      "Silver"
    end
  end

  def time_taken(day, star)
    if star.completed_at > day.end_time
      return ">24 hrs"
    else
      difference = (star.completed_at.utc - day.start_time).abs
      Time.at(difference).to_time_taken
    end
  end
end

app/views/days/_counters.html.erb
<div class="container-fluid">
  <div class="row row-cols-3 gx-1 mb-0">
    <div class="col">
      <div class="card bg-gold text-center align-middle pb-2 h-100">
        <span class="fs-2">
          <%= count_gold(day) %>
        </span>
        Gold + Silver
      </div>
    </div>

    <div class="col">
      <div class="card bg-silver text-center align-middle pb-2 h-100">
        <span class="fs-2">
          <%= count_silver(day) %>
        </span>
        Silver
      </div>
    </div>

    <div class="col">
      <div class="card text-center align-middle pb-2 h-100">
        <span class="fs-2">
          <%= count_incomplete(day) %>
        </span>
        Incomplete
      </div>
    </div>
  </div>
</div>

app/views/days/_day.html.erb
<div class="d-grid gap-4 mb-4">
  <%= link_to day.puzzle_url, class: 'btn btn-lg btn-secondary' do %>
    Today's Puzzle
  <% end %>
</div>

<h4>Today's stats <span class="fs-5 text-secondary fw-normal">day <%= day.number %></span></h4>

<%= render 'days/counters', day: day %>

<hr>

<h5>Today's fastest</h5>
<div class="row">
  <div class="col-lg-6">
    <h6>Gold</h6>
    <% if top_speeds(day, 2).any? %>
      <%= render 'days/gold_leaderboard', day: day, count: 3 %>
    <% else %>
      <p class="text-secondary text-center">
        You can still be the first to complete today's gold level!
      </p>
    <% end %>
  </div>
  <div class="col-lg-6">
    <h6>Silver</h6>
    <% if top_speeds(day, 1).any? %>
      <%= render 'days/silver_leaderboard', day: day, count: 3 %>
    <% else %>
      <p class="text-secondary text-center">
        You can still be the first to complete today's silver level!
      </p>
    <% end %>
  </div>
</div>

app/views/days/_gold_leaderboard.html.erb
<table class="table table-warning">
  <thead>
    <tr>
      <th>#</th>
      <th>Coalition</th>
      <th>Name</th>
      <th>Time Taken</th>
    </tr>
  </thead>
  <tbody>
    <% top_speeds(day, 2, count).each.with_index do |star, i| %>
      <tr class="align-middle">
        <td><strong><%= i + 1 %></strong></td>
        <% if star.participant.coalition %>
          <td style="background-color: <%= star.participant.coalition.color %>; text-align: center;">
            <%= image_tag star.participant.coalition.image_url, style: "min-width: 50%; max-width: 40px; max-height: 50px;", alt: star.participant.coalition.name %>
          </td>
        <% else %>
          <td class="bg-secondary-subtle"></td>
        <% end %>
        <td>
            <%= render star.participant %>
        </td>
        <td><%= time_taken(day, star) %></td>
      </tr>
    <% end %>
    <% if count_gold(day) > count %>
      <tr>
        <td colspan="4" class="text-secondary text-center">
          <%= link_to year_day_url(day.year.number, day.number), class: 'link-secondary' do %>
            Full leaderboard (+<%= count_gold(day) - count %>)
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/days/_silver_leaderboard.html.erb
<table class="table table-light">
  <thead>
    <tr>
      <th>#</th>
      <th>Coalition</th>
      <th>Name</th>
      <th>Time Taken</th>
    </tr>
  </thead>
  <tbody>
    <% top_speeds(day, 1, count).each.with_index do |star, i| %>
      <tr class="align-middle">
        <td><strong><%= i + 1 %></strong></td>
        <% if star.participant.coalition %>
          <td style="background-color: <%= star.participant.coalition.color %>; text-align: center;">
            <%= image_tag star.participant.coalition.image_url, style: "min-width: 50%; max-width: 40px; max-height: 50px;", alt: star.participant.coalition.name %>
          </td>
        <% else %>
          <td class="bg-secondary-subtle"></td>
        <% end %>
        <td>
            <%= render star.participant %>
        </td>
        <td><%= time_taken(day, star) %></td>
      </tr>
    <% end %>
    <% if count_silver_stars(day) > count %>
      <tr>
        <td colspan="4" class="text-secondary text-center">
          <%= link_to year_day_url(day.year.number, day.number), class: 'link-secondary' do %>
            Full leaderboard (+<%= count_silver_stars(day) - count %>)
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/days/show.html.erb
<div class="row mb-4">
  <%= link_to year_url(@day.year.number), class: "btn btn-outline-primary" do %>
    <%= bootstrap_icon 'caret-left' %>
    Back
  <% end %>
</div>

<div class="row mb-10">
  <h1>
    Day <%= @day.number %>
    <span class="text-secondary fs-3">
      <%= @day.year.number %>
    </span>
  </h1>
</div>

<div class="row gx-4">
  <div class="col-12 col-lg-4 mb-4">
    <h4>Stats</h4>
    <%= render 'days/counters', day: @day %>
  </div>

  <div class="col-12 col-lg-8">
    <h4>Gold leaderboard</h4>
    <%= render 'days/gold_leaderboard', day: @day, count: @day.year.participants.count %>
    <hr>
    <h4>Silver leaderboard</h4>
    <%= render 'days/silver_leaderboard', day: @day, count: @day.year.participants.count %>
  </div>
</div>