config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # The homepage should be a landing page for either new users
  # or a dashboard for existing users
  root 'pages#home'

  # Callback for logging in with 42 will create a session,
  # logging out will destroy one
  get '/auth/marvin/callback', to: 'sessions#create'
  get '/auth/failure',         to: 'sessions#failure'
  delete '/logout',            to: 'sessions#destroy'

  # Protection against unauthorized access in config/initializers/good_job.rb
  mount GoodJob::Engine => 'good_job'

  # We are not doing resourceful routing here because the user
  # you will be editing or updating is always clear, it is the
  # current user. For #new and #create, bindings also do not matter.
  get    '/users/new', to: 'users#new',     as: 'new_user'
  post   '/users',     to: 'users#create',  as: 'create_user'
  get    '/users',     to: 'users#edit',    as: 'edit_user'
  patch  '/users',     to: 'users#update',  as: 'update_user'
  delete '/users',     to: 'users#destroy', as: 'destroy_user'

  # We do some implicit routing here
  # When adding other routes, put them above this one
  # to avoid this catch-all from taking the request instead.
  get '/:year',      to: 'years#show', as: 'year'
  get '/:year/:day', to: 'days#show',  as: 'year_day'
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="col-md-10 offset-md-1 my-2">
    <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
      <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav>
  <div class="navbar">
    <div class="container">
      <span class="navbar-brand">
        <%= link_to root_url, class: 'navbar-brand' do %>
          Codam <span class="d-none d-md-inline">Advent of Code</span> Leaderboard
        <% end %>

        <span class="badge bg-secondary">
          <%# This is a crime against mvc %>
          <% if Year.find_by(number: page_year.to_i - 1) %>
            <%= link_to year_url(page_year.to_i - 1), class: 'link-underline link-underline-opacity-0' do %>
              <%= bootstrap_icon 'caret-left' %>
            <% end %>
          <% end %>

          <%= page_year %>

          <% if Year.find_by(number: page_year.to_i + 1) %>
            <%= link_to year_url(page_year.to_i + 1), class: 'link-underline link-underline-opacity-0' do %>
              <%= bootstrap_icon 'caret-right' %>
            <% end %>
          <% end %>
        </span>
      </span>

      <span class="d-flex navbar-text">
        <% if logged_in? %>
          <span class="me-2 navbar-avatar">
            <% if current_user.photo_url %>
              <img src="<%= current_user.photo_url %>" class="rounded inline-avatar">
            <% end %>
            <%= current_user.username %>
            <% if current_user.admin? %>
              <%= link_to new_user_url, 'data-turbo-frame': 'edit-user-frame', class: 'ms-2 link-underline link-underline-opacity-0' do %>
                <%= bootstrap_icon 'person-plus-fill' %>
              <% end %>
            <% end %>
            <%= link_to edit_user_url, 'data-turbo-frame': 'edit-user-frame', class: 'ms-2 link-underline link-underline-opacity-0' do %>
              <%= bootstrap_icon 'gear-fill' %>
            <% end %>
          </span>
          <%= form_tag('/logout', method: 'delete', data: {turbo: false}) do %>
            <button type='submit' class="btn btn-outline-danger">Log out</button>
          <% end %>
        <% else %>
          <%= form_tag('/auth/marvin', method: 'post', data: {turbo: false}) do %>
            <button type='submit' class="btn btn-outline-primary">Log in with 42</button>
          <% end %>
        <% end %>
      </span>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-bs-theme="dark">
  <head>
    <title><%= page_title(yield :title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <% if ENV['SENTRY_DSN'] %>
      <%= Sentry.get_trace_propagation_meta.html_safe %>
    <% end %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <main>
      <div class="container">
        <% if logged_in? && !current_user.aoc_user_id? %>
          <%= render 'users/edit' %>
        <% else %>
          <%= render 'users/empty_frame' %>
        <% end %>

        <%= render 'layouts/flash' %>

        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/no_turbo_frame.html.erb
<!DOCTYPE html>
<html data-bs-theme="dark">
  <head>
    <title><%= page_title(yield :title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <main>
      <div class="container">
        <%= render 'layouts/flash' %>

        <%= yield %>
      </div>
    </main>
  </body>
</html>